### ISSUE TITLE
tinc reçoit erreur "Bogus data received from" à la connexion

### ISSUE THREAD

**Issue by EtienneHelfer** [ptorrent/webleIoTGateway#27]
si tinc reçoit l'erreur 
"Bogus data received from" à la connexion

![image](https://user-images.githubusercontent.com/35633370/60300431-3c8e9280-992f-11e9-875e-a27858de039a.png)

Cela veut dire que les fichiers dans le dossier hosts sont pas identiques / corrompus. Il faudrait alors les corriger en prenant la version sur le serveur et redémarrer tinc

**Comment by ptorrent** [comment]
done
