### ISSUE TITLE
value_string empty space at the end (helpers.js)

### ISSUE THREAD

**Issue by ptorrent** [ptorrent/webleIoTGateway#28]
![image](https://user-images.githubusercontent.com/6083644/61160538-0a209000-a500-11e9-8938-916d3205c748.png)

Constaté sur une adresse virtuelle, pas regardé sur les autres drivers

**Comment by ptorrent** [comment]
![image](https://user-images.githubusercontent.com/6083644/61169025-1552da80-a557-11e9-87b0-ccfe147b18d4.png)

**Comment by EtienneHelfer** [comment]
c'est normal
